from dotenv import load_dotenv
from pydantic import BaseModel
from langchain_groq import ChatGroq
from langchain_core.output_parsers import PydanticOutputParser
from langgraph.prebuilt import create_react_agent


# --------------------------------------------------
# ENV
# --------------------------------------------------
load_dotenv()


# --------------------------------------------------
# STRUCTURED OUTPUT SCHEMA
# --------------------------------------------------
class ChristmasWish(BaseModel):
    message: str
    blessing: str


# --------------------------------------------------
# LLM + OUTPUT PARSER
# --------------------------------------------------
llm = ChatGroq(model="llama-3.3-70b-versatile")
parser = PydanticOutputParser(pydantic_object=ChristmasWish)


# --------------------------------------------------
# SYSTEM PROMPT (as string for LangGraph)
# --------------------------------------------------
system_prompt = f"""
You are a friendly assistant that creates warm Christmas wishes.

Generate a heartfelt Christmas wish with a meaningful message, and a blessing.

Return ONLY the structured output below.
Do NOT add explanations or extra text.

{parser.get_format_instructions()}
"""


# --------------------------------------------------
# CREATE AGENT (LangGraph) - NO TOOLS
# --------------------------------------------------
agent = create_react_agent(
    model=llm,
    tools=[],  # Empty tools list
    prompt=system_prompt,
)


# --------------------------------------------------
# RUN
# --------------------------------------------------
def wish(type,name):
    print("🎄 Generating Christmas Wish...\n")

    result = agent.invoke(
        {"messages": [("human", f"Generate a beautiful Christmas wish for {type}(GR for a group of people, ID for one person)")]}
    )

    # LangGraph returns messages, last one is final answer
    final_output = result["messages"][-1].content

    try:
        structured = parser.parse(final_output)
        # print("✅ Christmas Wish Generated\n")
        # print(f"🎅 Dear {name},")
        # print(f"🎁 {structured.message}")
        # print(f"⭐ {structured.blessing}\n")
        # print("[This Message was generated by AI, if theres anything about the message, blame the AI not me, Merry Christmas]")
        return(f"Dear {name}, {structured.message} ⭐ {structured.blessing}, Here are some jolly melodies to listen to during this festive season. "
               f"https://open.spotify.com/playlist/6kc6rxvGA0YrkEDUkwAlmv?si=d3n2vV9DRh-lpKUobhfF4g"
               f" [This Message was generated by AI, if theres anything weird about the message, blame the AI not me, Merry Christmas]")

    except Exception as e:
        print("❌ Parsing failed")
        print(e)
        print("\nRaw output:\n")
        print(final_output)


if __name__ == "__main__":
    wish()